name: "🐛 Bug report"
description: Create a bug report to help us improve
title: "[🐛] Bug Report:"
labels: [bug]
assignees:
  - TheDanniCraft

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **To Reproduce**
        Steps to reproduce the behavior:
        
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    id: workflow-link
    attributes:
      label: Workflow Link
      description: Paste a link to the related workflow.
      placeholder: https://github.com/owner/repo/actions/workflows/filename.yml
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: e.g. Ubuntu 20.04

  - type: input
    id: runner-version
    attributes:
      label: Runner Version
      description: e.g. 2.278.0

  - type: input
    id: additional-tools
    attributes:
      label: Additional Tools
      description: e.g. Docker, Node.js

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any other relevant information.