name: "🛠️ Feature request"
description: Suggest an idea for this project with more detail
title: "[🛠️] Feature Request:"
labels: ["enhancement"]
assignees:
    - TheDanniCraft
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: What problem does this feature address? (e.g., I'm frustrated when...)
      placeholder: Describe the problem or pain point.
    validations:
      required: true
  - type: textarea
    id: beneficiaries
    attributes:
      label: Who benefits?
      description: Describe the use case or target audience for this feature.
      placeholder: Who will use or benefit from this feature?
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: How important is this feature?
      description: Select the importance level.
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What do you want to happen? Please be clear and concise. Add mockups, diagrams, or workflow examples if possible.
      placeholder: Describe your proposed solution.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered? Why were they not chosen?
      placeholder: List any alternatives and why you didn't choose them.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples to help explain your request.
      placeholder: Provide extra details, links, or images.